os:
  - linux
  - osx

compiler:
  - clang
  - gcc

language: cpp

matrix:
  include:
     - os: linux
       sudo: required
       dist: trusty
       compiler: gcc
     - os: linux
       sudo: required
       dist: trusty
       compiler: clang
     - os: osx
       compiler: clang
  exclude:
     - os: linux
       dist: precise
       compiler: gcc
     - os: osx
       compiler: gcc

script: cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y cmake python-dev g++ libpcre3 libpcre3-dev libgmp3-dev uuid-dev python-sympy; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgtkmm-3.0-dev libjsoncpp-dev libboost-all-dev libgmp-dev libsqlite3-dev; fi

   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake boost boost-python pcre gmp jsoncpp python pkgconfig ossp-uuid gtkmm3 gnome-icon-theme; fi
